force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <displayFormat>EP{0000000}</displayFormat>
        <label>Episode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Episod_Number__c.field-meta.xml
<CustomField>
    <fullName>Episod_Number__c</fullName>
    <label>Episode Number</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Season Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Season_Number__c.field-meta.xml
<CustomField>
    <fullName>Season_Number__c</fullName>
    <label>Season Number</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Season__c/fields/Tv_Serie__c.field-meta.xml
<CustomField>
    <fullName>Tv_Serie__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tv Serie</label>
    <referenceTo>Tv_Serie__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tv_Serie__c/Tv_Serie__c.object-meta.xml
<CustomObject>
    <label>Tv Serie</label>
    <nameField>
        <label>Tv Serie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tv Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {

    public static Tv_Serie__c createTvSerie(String TvSerieName){
        return new Tv_Serie__c(Name=TvSerieName);
    }
    public static Season__c createSeason(Id tvSerieId, Integer seasonNumber){
        return new Season__c(Tv_Serie__c = tvSerieId, Season_Number__c = seasonNumber);
    }
    public static Episode__c createEpisode(Id seasonId, Integer episodeNumber){
        return new Episode__c(Season__c = seasonId, Episod_Number__c = episodeNumber);
    }
}