force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <displayFormat>EP{0000000}</displayFormat>
        <label>Episode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Episod_Number__c.field-meta.xml
<CustomField>
    <fullName>Episod_Number__c</fullName>
    <label>Episode Number</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Season Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EpisodesController.cls
public with sharing class EpisodesController {
    @AuraEnabled(cacheable=true)
    public static List<Episode__c> getEpisodesBySeason(Id seasonId){
        return[
            SELECT Id, Name, Episod_Number__c, Description__c
            FROM Episode__c
            WHERE Season__c =:seasonId
            WITH SECURITY_ENFORCED
            ORDER BY Episod_Number__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Episode__c getEpisodeById(Id episodeId){
        List<Episode__c> tempList = [
            SELECT Id, Name, Episod_Number__c, Description__c, CreatedDate
            FROM Episode__c
            WHERE Id =:episodeId
            WITH SECURITY_ENFORCED
        ];

        if(tempList.size()==0){
            return null;
        }else{
            return tempList[0];
        }
    }


    @AuraEnabled(cacheable=true)
    public static Integer getNumberOfEpisods(Id seasonId){

        List<Episode__c> tempList = [
            SELECT Id
            FROM Episode__c
            WHERE Season__c =:seasonId
            WITH SECURITY_ENFORCED
        ];

        return tempList.size();

    }
}